<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/Prj_SOAPActivities/SharedResorces/Schemas/Schema.xsd" xmlns:tns="http://xmlns.example.com/1556367796128" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.tibco.com/schemas/Prj_SOAPActivities/SharedResorces/Schemas/Schema1.xsd" targetNamespace="http://xmlns.example.com/1556367796128">
    <import namespace="http://www.tibco.com/schemas/Prj_SOAPActivities/SharedResorces/Schemas/Schema1.xsd" location="../Schemas/outputschema.xsd"/>
    <import namespace="http://www.tibco.com/schemas/Prj_SOAPActivities/SharedResorces/Schemas/Schema.xsd" location="../Schemas/inputschema.xsd"/>
    <message name="InputMessage">
        <part name="inputmessage" element="ns:EmployeeData"/>
    </message>
    <message name="OutputMessage">
        <part name="outputmessage" element="ns2:EmployeeDetails"/>
    </message>
    <portType name="PortType">
        <operation name="Operation">
            <input message="tns:InputMessage"/>
            <output message="tns:OutputMessage"/>
        </operation>
    </portType>
</definitions>